name: "Run Gatling (Java-Maven)"
description: "Runs Gatling tests for the Maven project"

inputs:
  simulation:
    required: true
  test_duration:
    required: true
  ramp_up_duration:
    required: true
  secret_id:
    required: false
    secret: true
  secret_key:
    required: false
    secret: true

runs:
  using: "composite"
  steps:

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Run Gatling Tests
      shell: bash
      run: |
        ./java-maven/actions/run-gatling.sh \
        ${{ inputs.simulation }} \
        ${{ inputs.test_duration }} \
        ${{ inputs.ramp_up_duration }} \
        ${{ github.workspace }} \
        ${{ inputs.secret_id }} \
        ${{ inputs.secret_key }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gatling-reports-java-maven-${{ github.run_number }}
        path: |
          ${{ github.workspace }}/java-maven/target/gatling/**
        if-no-files-found: warn