name: "Run Gatling (Java-Gradle)"
description: "Runs Gatling tests for the Gradle project"

inputs:
  simulation:
    required: true
  test_duration:
    required: true
  ramp_up_duration:
    required: true

runs:
  using: "composite"
  steps:
#    - name: Debug current directory
#      shell: bash
#      run: |
#        echo "Current directory:"
#        pwd
#        echo ""
#        echo "Workspace variable:"
#        echo "$GITHUB_WORKSPACE"
#        echo ""
#        echo "List files here:"
#        ls -la
#
#    - name: Debug script header
#      shell: bash
#      run: |
#        ls -la ./java-gradle/actions
#        file ./java-gradle/actions/run-gatling.sh
#        head -n 1 ./java-gradle/actions/run-gatling.sh | cat -A

    - name: Run Gatling Tests
      shell: bash
      run: |
        ./java-gradle/actions/run-gatling.sh \
        ${{ inputs.simulation }} \
        ${{ inputs.test_duration }} \
        ${{ inputs.ramp_up_duration }} \
        ${{ github.workspace }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gatling-reports-java-gradle-${{ github.run_number }}
        path: |
          ${{ github.workspace }}/java-gradle/target/gatling/**
        if-no-files-found: warn