on:
  workflow_dispatch:
    inputs:
      project:
        description: "Enter name of test project to run"
        required: true
        default: "java-maven"
      simulation:
        description: "Enter name of the simulation"
        required: true
        default: "LoadTest"
      ramp_up_duration:
        description: "Load ramp up duration"
        required: true
        default: "2"
      test_duration:
        description: "Load duration (steady load)"
        required: true
        default: "2"

jobs:
  gatling-tests:
    name: PerfTest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Run java-maven action
        if: ${{ github.event.inputs.project == 'java-maven' }}
        uses: ./java-maven/actions
        with:
          simulation: ${{ github.event.inputs.simulation }}
          test_duration: ${{ github.event.inputs.test_duration }}
          ramp_up_duration: ${{ github.event.inputs.ramp_up_duration }}
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Run java-gradle action
        if: ${{ github.event.inputs.project == 'java-gradle' }}
        uses: ./java-gradle/actions
        with:
          simulation: ${{ github.event.inputs.simulation }}
          test_duration: ${{ github.event.inputs.test_duration }}
          ramp_up_duration: ${{ github.event.inputs.ramp_up_duration }}
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Fail if project input is unsupported
        if: ${{ github.event.inputs.project != 'java-maven' && github.event.inputs.project != 'java-gradle' }}
        run: |
          echo "Unsupported project: ${{ github.event.inputs.project }}"
          exit 1