on:
  workflow_dispatch:
    inputs:
      project:
        description: "Enter name of test project to run"
        required: true
        type: choice
        options:
          - java-maven
          - jave-gradle
          - javascript
      simulation:
        description: "Enter name of the simulation"
        required: true
        type: choice
        options:
          - LoadTest
          - StressTest
          - BreakpointTest
      ramp_up_duration:
        description: "Load ramp up duration"
        required: true
        default: "2"
      test_duration:
        description: "Load duration (steady load)"
        required: true
        default: "2"

jobs:
  gatling-tests:
    name: PerfTest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run java-maven action
        if: ${{ github.event.inputs.project == 'java-maven' }}
        uses: ./java-maven/actions
        with:
          simulation: ${{ github.event.inputs.simulation }}
          test_duration: ${{ github.event.inputs.test_duration }}
          ramp_up_duration: ${{ github.event.inputs.ramp_up_duration }}
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Run java-gradle action
        if: ${{ github.event.inputs.project == 'java-gradle' }}
        uses: ./java-gradle/actions
        with:
          simulation: ${{ github.event.inputs.simulation }}
          test_duration: ${{ github.event.inputs.test_duration }}
          ramp_up_duration: ${{ github.event.inputs.ramp_up_duration }}
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}